# -*- coding: utf-8 -*-
"""knishikawa_CIS340_Lab5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ax-uWMhGZcTn3XujWIFd6D35dhW7vrrv

File name: Knishikawa_CIS340_lab4
    Author Name: Ken Nishikawa
    Date of Creation: 10/23/25
    History of Modification: 10/26/25
    Description of what the module(file) does: lab 4

•	Define constants: pounds→ounces, size weights, and all recipe percentages.
	•	compute_ingredients(type_num, size_letter):
	•	Nested if by cake type, then size.
	  •	Pick total ounces.
	  •	Compute each ingredient amount.
	  •	Return (cake_name, size_name, items_list).
	•	print_ingredients(size_name, cake_name, items):
	  •	Print header.
	  •	Loop items and print with formatting (no arithmetic here).
	•	main():
	  •	[Input] read type and size.
	  •	[Calculate] call compute_ingredients.
	  •	[Output] call print_ingredients.
	  •	(Optional commented test code) verify totals.
"""

# constants (all lowercase)
lb_to_oz = 16
regular_lb = 4
large_lb = 7
regular_oz = regular_lb * lb_to_oz
large_oz = large_lb * lb_to_oz

# chocolate cake %
cc_ing_a = 0.158
cc_ing_b = 0.245
cc_ing_c = 0.056
cc_ing_d = 0.541

# red velvet cake %
rvc_ing_a = 0.224
rvc_ing_b = 0.224
rvc_ing_c = 0.240
rvc_ing_d = 0.179
rvc_ing_e = 0.133

# lemon cake %
lc_ing_a = 0.385
lc_ing_d = 0.358  # (lemon_b -> lc_ing_d)
lc_ing_c = 0.257


def compute_ingredients(cake_type, size_choice):
    """
    ***************************************************************************
    function: compute_ingredients
    parameters:
        cake_type (int) - 1=chocolate, 2=red velvet, 3=lemon
        size_choice (str) - 'r' for regular, 'l' for large
    outputs: none
    returns:
        tuple[str, str, list[tuple[str, float]]]
        -> (cake_name, size_name, [(ingredient_label, ounces), ...])
    author: ken nishikawa
    date: october 27, 2025
    modifications:
        renamed
    description:
        calculates ingredient amounts in ounces based on cake type and size.
        uses nested if constructs. all arithmetic stays in this function.
    ***************************************************************************
    """

    size_choice = str(size_choice).strip().lower()

    if cake_type == 1:
        cake_name = "chocolate"
        if size_choice == "r":
            total_oz = regular_oz
            size_name = "regular"
        else:
            total_oz = large_oz
            size_name = "large"

        a = total_oz * cc_ing_a
        b = total_oz * cc_ing_b
        c = total_oz * cc_ing_c
        d = total_oz * cc_ing_d

        items = [
            ("ingredient a", a),
            ("ingredient b", b),
            ("ingredient c", c),
            ("ingredient d", d),
        ]

    elif cake_type == 2:
        cake_name = "red velvet"
        if size_choice == "r":
            total_oz = regular_oz
            size_name = "regular"
        else:
            total_oz = large_oz
            size_name = "large"

        a = total_oz * rvc_ing_a
        b = total_oz * rvc_ing_b
        c = total_oz * rvc_ing_c
        d = total_oz * rvc_ing_d
        e = total_oz * rvc_ing_e

        items = [
            ("ingredient a", a),
            ("ingredient b", b),
            ("ingredient c", c),
            ("ingredient d", d),
            ("ingredient e", e),
        ]

    else:
        cake_name = "lemon"
        if size_choice == "r":
            total_oz = regular_oz
            size_name = "regular"
        else:
            total_oz = large_oz
            size_name = "large"

        a = total_oz * lc_ing_a
        b = total_oz * lc_ing_d
        c = total_oz * lc_ing_c

        items = [
            ("ingredient a", a),
            ("ingredient b", b),
            ("ingredient c", c),
        ]

    return cake_name, size_name, items


def print_ingredients(size_name, cake_name, items):
    """
    ***************************************************************************
    function: print_ingredients
    parameters:
        size_name (str)
        cake_name (str)
        items (list[tuple[str, float]]) - label and amount in ounces
    outputs:
        prints formatted ingredient list to the console
    returns: none
    author: ken nishikawa
    date: october 27, 2025
    modifications: none
    description:
        outputs header and each ingredient amount with formatting only.
        no arithmetic is performed in this output stage.
    ***************************************************************************
    """

    print("\n{} {} ingredient list:".format(size_name, cake_name))
    line_fmt = "{:<12}:  {:5.1f} oz"
    for label, ounces in items:
        print(line_fmt.format(label, ounces))


def main():
    """
    ***************************************************************************
    function: main
    parameters: none
    outputs:
        prompts user and prints results to the console
    returns: none
    author: ken nishikawa
    date: october 27, 2025
    modifications:
        updated all remaining uppercase text to lowercase.
    description:
        program entry following 3 steps:
        [input] read cake type/size
        [calculate] compute ingredient amounts
        [output] print formatted ingredient list
    ***************************************************************************
    """


    # input
    type_text = input("please select cake type; enter 1 for chocolate, 2 for red velvet and 3 for lemon: ")
    size_text = input("\nplease select cake size; enter l for large, r for regular: ")

    cake_type = int(type_text)  # scope: assume valid input
    size_choice = size_text

    # calculate
    cake_name, size_name, items = compute_ingredients(cake_type, size_choice)

    # output
    print_ingredients(size_name, cake_name, items)

# paste execution interface and output to the bottom of the .py file.
if __name__ == "__main__":
    main()